dist: xenial
before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst apertium lttoolbox apertium-dev lttoolbox-dev libhfst-dev cg3 python3-setuptools python3-lxml python3-libhfst apcalc
    - wget https://gist.githubusercontent.com/IlnarSelimcan/c726419d16a6802643626d1219730b41/raw/519488c12acde8eddb3acdac3b4f53bf53739838/install-apertium-quality.sh -O - | sudo bash
script:
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/site-packages
    - ./autogen.sh
    - make
    - make check
notifications:
    irc:
        channels:
            - "chat.freenode.net#apertium"
        on_failure: change
        on_success: never
    email:
        recipients:
            - ilnar@selimcan.org
        on_failure: always
        on_success: never
